# Generated by Django 5.2.17 on 2026-09-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('indicator', 'indicator'), ('release_group', 'release group'), ('event_release', 'event release'), ('instrument', 'instrument'), ('study_run', 'study run'), ('market_event', 'market event'), ('general', 'general')], max_length=20)),
                ('scope_id', models.IntegerField(blank=True, null=True)),
                ('body_md', models.TextField()),
                ('basis', models.CharField(choices=[('literature', 'literature — cited, peer-reviewed'), ('computed', 'computed — derived from our own measurements'), ('generated', 'generated — model-written, labelled as such'), ('user_note', 'user note')], max_length=16)),
                ('epistemic_status', models.CharField(choices=[('established', 'ESTABLISHED — peer-reviewed and replicated'), ('estimate', 'ESTIMATE — measured from our own sample'), ('hypothesis', 'HYPOTHESIS — not established by this tool'), ('unknown', 'UNKNOWN — undetermined, and we say so')], max_length=16)),
                ('citation', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'commentary',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id'], name='commentary__scope_t_b4e84b_idx')],
            },
        ),
    ]
