# Generated by Django 5.2.17 on 2026-09-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12, unique=True)),
                ('base_ccy', models.CharField(max_length=3)),
                ('quote_ccy', models.CharField(max_length=3)),
                ('pip_size', models.DecimalField(decimal_places=8, max_digits=12)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_utc', models.DateTimeField(db_index=True)),
                ('end_ts_utc', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('dislocation', 'dislocation / flash crash'), ('policy_shock', 'unscheduled policy shock'), ('crisis', 'crisis period'), ('holiday', 'market holiday / thin liquidity'), ('other', 'other')], default='other', max_length=20)),
                ('regime', models.CharField(blank=True, choices=[('pre_crisis', 'pre-crisis (2007–08)'), ('crisis', 'crisis (2008–09)'), ('zirp_qe', 'ZIRP/QE (2010–15)'), ('normalisation', 'normalisation (2015–19)'), ('covid', 'COVID (2020–21)'), ('inflation_hiking', 'inflation/hiking (2022–23)'), ('post_hiking', 'post-hiking (2024–)')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('instruments', models.ManyToManyField(blank=True, related_name='market_events', to='prices.instrument')),
            ],
            options={
                'ordering': ['ts_utc'],
            },
        ),
        migrations.CreateModel(
            name='PriceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the covered month.')),
                ('bar_count', models.IntegerField(default=0)),
                ('expected_bar_count', models.IntegerField(default=0)),
                ('gap_count', models.IntegerField(default=0)),
                ('first_ts_utc', models.DateTimeField(blank=True, null=True)),
                ('last_ts_utc', models.DateTimeField(blank=True, null=True)),
                ('parquet_path', models.TextField(blank=True, help_text='Relative to settings.PARQUET_DIR.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.fetchrun')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='prices.instrument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
            options={
                'ordering': ['instrument', 'source', 'month'],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'source', 'month'), name='uniq_coverage_month')],
            },
        ),
    ]
