# Generated by Django 5.2.17 on 2026-09-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
        ('sources', '0002_fetchrun_bars_written_fetchrun_preview_only_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecoverage',
            options={'ordering': ['instrument', 'source', 'timeframe', 'month']},
        ),
        migrations.RemoveConstraint(
            model_name='pricecoverage',
            name='uniq_coverage_month',
        ),
        migrations.AddField(
            model_name='pricecoverage',
            name='timeframe',
            field=models.CharField(choices=[('m1', '1 minute'), ('m15', '15 minutes'), ('h1', '1 hour'), ('d1', '1 day')], db_index=True, default='m1', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='pricecoverage',
            constraint=models.UniqueConstraint(fields=('instrument', 'source', 'timeframe', 'month'), name='uniq_coverage_month'),
        ),
    ]
