# Generated by Django 5.2.17 on 2026-09-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD — United States'), ('EUR', 'EUR — Euro area'), ('GBP', 'GBP — United Kingdom'), ('JPY', 'JPY — Japan'), ('CHF', 'CHF — Switzerland'), ('AUD', 'AUD — Australia'), ('CAD', 'CAD — Canada'), ('NZD', 'NZD — New Zealand')], max_length=3)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['currency', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(choices=[('USD', 'USD — United States'), ('EUR', 'EUR — Euro area'), ('GBP', 'GBP — United Kingdom'), ('JPY', 'JPY — Japan'), ('CHF', 'CHF — Switzerland'), ('AUD', 'AUD — Australia'), ('CAD', 'CAD — Canada'), ('NZD', 'NZD — New Zealand')], db_index=True, max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('canonical_code', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('mapping_status', models.CharField(choices=[('auto', 'auto — created by an ingest, not yet reviewed'), ('mapped', 'mapped — canonical code assigned by hand'), ('ignored', 'ignored — deliberately out of scope')], db_index=True, default='auto', max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('frequency', models.CharField(blank=True, max_length=32)),
                ('importance', models.IntegerField(choices=[(0, 'unknown'), (1, 'low'), (2, 'medium'), (3, 'high')], default=0)),
                ('explainer_md', models.TextField(blank=True, help_text='Hand-written explainer (§6.10 / P6). Data, not commentary.')),
                ('transmission_channel', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='calendar_data.releasegroup')),
            ],
            options={
                'ordering': ['currency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_period', models.CharField(help_text="Normalised label for the period the number describes, e.g. '2024-01', '2024-Q1'. Part of the identity key (§4.4).", max_length=64)),
                ('reference_period_start', models.DateField(blank=True, null=True)),
                ('revision_no', models.PositiveSmallIntegerField(default=0)),
                ('release_time_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_time_utc', models.DateTimeField(blank=True, null=True)),
                ('trading_day', models.DateField(blank=True, help_text='Derived, anchored to 17:00 America/New_York (§4.1). Never inferred from the UTC calendar date.', null=True)),
                ('actual_first_print', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('actual_current', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('forecast_point_in_time', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('forecast_stored', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('forecast_modelled', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('previous', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('revised_previous', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('surprise_raw', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('surprise_z', models.FloatField(blank=True, null=True)),
                ('timestamp_confidence', models.CharField(choices=[('exact', 'exact — second-level release time from an authoritative source'), ('minute', 'minute — rounded to the minute'), ('date_only', 'date only — no usable time of day'), ('inferred', 'inferred — reconstructed from schedule or convention')], default='inferred', max_length=16)),
                ('forecast_provenance', models.CharField(choices=[('point_in_time', 'point in time — captured before the release'), ('vendor_stored', 'vendor stored — may have been updated after the fact'), ('unverified', 'unverified — scraped dataset of unknown provenance'), ('modelled', 'modelled — §6.7 baseline, not a survey consensus'), ('none', 'none')], default='none', max_length=16)),
                ('actual_provenance', models.CharField(choices=[('first_print', 'first print — the number as originally published'), ('current_may_be_revised', 'current — may include later revisions'), ('unknown', 'unknown')], default='unknown', max_length=24)),
                ('cross_source', models.CharField(choices=[('agree', 'agree — sources within tolerance'), ('disagree', 'disagree — outside tolerance, both values retained'), ('single_source', 'single source — nothing to compare against')], default='single_source', max_length=16)),
                ('vol_check', models.CharField(choices=[('confirmed', 'confirmed — spike within ±2 minutes'), ('offset', 'offset — spike found, but not where the timestamp says'), ('no_spike', 'no spike — nothing measurable happened here'), ('not_checked', 'not checked')], default='not_checked', max_length=16)),
                ('confounded', models.BooleanField(default=False, help_text='Another event within ±15 min. Window scales with horizon (§6.6).')),
                ('source_map_json', models.JSONField(blank=True, default=dict, help_text='field -> source key. The merged row is a composite, not a copy of one source (§4.4).')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='calendar_data.indicator')),
                ('release_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='calendar_data.releasegroup')),
            ],
            options={
                'ordering': ['-release_time_utc'],
            },
        ),
        migrations.CreateModel(
            name='SourceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_json', models.JSONField(default=dict)),
                ('event_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='calendar_data.eventrelease')),
                ('fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.fetchrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='ValueRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(max_length=64)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('event_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='calendar_data.eventrelease')),
                ('fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.fetchrun')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(help_text='Stable identifier at the source (MT5 event_id, FF title, …).', max_length=200)),
                ('source_name', models.CharField(blank=True, max_length=300)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='calendar_data.indicator')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='sources.source')),
            ],
            options={
                'ordering': ['source', 'currency', 'source_name'],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_key'), name='uniq_alias_per_source')],
            },
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['mapping_status', 'currency'], name='calendar_da_mapping_d19d91_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrelease',
            index=models.Index(fields=['release_time_utc', 'indicator'], name='calendar_da_release_cc383f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrelease',
            index=models.Index(fields=['trading_day'], name='calendar_da_trading_46075b_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrelease',
            constraint=models.UniqueConstraint(fields=('indicator', 'reference_period', 'revision_no'), name='uniq_release_identity'),
        ),
        migrations.AddIndex(
            model_name='sourceobservation',
            index=models.Index(fields=['event_release', 'source'], name='calendar_da_event_r_ed78e4_idx'),
        ),
        migrations.AddIndex(
            model_name='valuerevision',
            index=models.Index(fields=['event_release', 'field'], name='calendar_da_event_r_9fe3a9_idx'),
        ),
    ]
