# Generated by Django 5.2.17 on 2026-09-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrelease',
            name='vol_check_offset_min',
            field=models.IntegerField(blank=True, help_text='Signed minutes from the stored timestamp to where the volatility spike actually was. 0 when the spike is in the stored bar.', null=True),
        ),
        migrations.AddField(
            model_name='eventrelease',
            name='vol_check_ratio',
            field=models.FloatField(blank=True, help_text='Movement in the stored bar as a multiple of what this pair normally does in the same weekday-and-hour slot.', null=True),
        ),
        migrations.AlterField(
            model_name='eventrelease',
            name='vol_check',
            field=models.CharField(choices=[('confirmed', 'confirmed — spike within ±2 minutes'), ('confirmed_hour', 'confirmed at hour resolution — spike in the stored hour'), ('offset', 'offset — spike found, but not where the timestamp says'), ('no_spike', 'no spike — nothing measurable happened here'), ('uncheckable', 'uncheckable — no bars, or no usable normal to compare against'), ('not_checked', 'not checked')], default='not_checked', max_length=16),
        ),
    ]
