# Generated by Django 5.2.17 on 2026-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_data', '0002_eventrelease_vol_check_offset_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrelease',
            name='vol_check',
            field=models.CharField(choices=[('confirmed', 'confirmed — spike within ±2 minutes'), ('confirmed_hour', 'confirmed at hour resolution — spike in the stored hour'), ('offset', 'offset — spike found, but not where the timestamp says'), ('no_spike', 'no spike — nothing measurable happened here'), ('confounded', 'confounded — the nearby spike belongs to a bigger release'), ('uncheckable', 'uncheckable — no bars, or no usable normal to compare against'), ('not_checked', 'not checked')], default='not_checked', max_length=16),
        ),
    ]
