# Generated by Django 5.2.17 on 2026-09-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_data', '0003_alter_eventrelease_vol_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='concept',
            field=models.CharField(blank=True, choices=[('labour', 'labour — employment, unemployment, claims, wages'), ('inflation', 'inflation — CPI, PPI, price indices'), ('policy_rate', 'policy rate — decisions, minutes, facilities'), ('growth', 'growth — GDP, production, productivity'), ('survey', 'survey — PMI, sentiment, business confidence'), ('consumption', 'consumption — retail sales, spending, durables'), ('housing', 'housing — permits, starts, prices, mortgages'), ('trade', 'trade — balance, current account'), ('energy', 'energy — oil and gas inventories'), ('fiscal', 'fiscal — budget, debt, auctions'), ('speech', 'speech — no number, so no direction'), ('political', 'political — elections, votes, rulings'), ('', 'unclassified')], db_index=True, default='', help_text="§6.4's pooling axis, derived from the name. Not the same thing as canonical_code, which identifies one series across sources.", max_length=16),
        ),
    ]
