# Generated by Django 5.2.17 on 2026-09-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_data', '0001_initial'),
        ('prices', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('ts_utc', models.DateTimeField(db_index=True)),
                ('cum_abn_move_1d', models.FloatField(blank=True, null=True)),
                ('cum_abn_move_3d', models.FloatField(blank=True, null=True)),
                ('cum_abn_move_5d', models.FloatField(blank=True, null=True)),
                ('cum_abn_move_10d', models.FloatField(blank=True, null=True)),
                ('cum_surprise_1d', models.FloatField(blank=True, null=True)),
                ('cum_surprise_3d', models.FloatField(blank=True, null=True)),
                ('cum_surprise_5d', models.FloatField(blank=True, null=True)),
                ('days_since_tier1', models.FloatField(blank=True, null=True)),
                ('rel_volatility', models.FloatField(blank=True, help_text='Realised vol relative to its own trailing average.', null=True)),
                ('regime', models.CharField(blank=True, choices=[('pre_crisis', 'pre-crisis (2007–08)'), ('crisis', 'crisis (2008–09)'), ('zirp_qe', 'ZIRP/QE (2010–15)'), ('normalisation', 'normalisation (2015–19)'), ('covid', 'COVID (2020–21)'), ('inflation_hiking', 'inflation/hiking (2022–23)'), ('post_hiking', 'post-hiking (2024–)')], max_length=20)),
                ('engine_version', models.CharField(default='', max_length=32)),
            ],
            options={
                'ordering': ['currency', 'ts_utc'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'ts_utc'), name='uniq_currency_state')],
            },
        ),
        migrations.CreateModel(
            name='StudySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('spec_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='studies.studyspec')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='StudyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('sample', models.CharField(choices=[('explore', 'explore (2007–2018)'), ('holdout', 'holdout (2019–)'), ('full', 'full')], default='full', max_length=16)),
                ('n_observations', models.IntegerField(default=0)),
                ('engine_version', models.CharField(blank=True, max_length=32)),
                ('result_ref', models.TextField(blank=True, help_text='Path or cache key for the result set.')),
                ('notes', models.TextField(blank=True)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_run', to='sources.job')),
                ('study_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='studies.studyspec')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('established', 'ESTABLISHED — peer-reviewed and replicated'), ('estimate', 'ESTIMATE — measured from our own sample'), ('hypothesis', 'HYPOTHESIS — not established by this tool'), ('unknown', 'UNKNOWN — undetermined, and we say so')], default='hypothesis', max_length=16)),
                ('note_md', models.TextField(blank=True)),
                ('study_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypotheses', to='studies.studyspec')),
            ],
            options={
                'verbose_name_plural': 'hypotheses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(db_index=True, max_length=16)),
                ('window_scheme', models.CharField(choices=[('fixed', 'fixed ladder (§3.2) — comparability across events; the default'), ('until_next_own', "until the same currency's next tier-1 event"), ('until_next_either', "until either currency's next tier-1 event"), ('until_next_any', 'until the next event of any importance')], default='fixed', max_length=24)),
                ('window_seconds', models.IntegerField(help_text='Signed. Equals the ladder offset for fixed windows; measured for event-anchored ones (§3.2b).')),
                ('ret', models.FloatField(blank=True, help_text='Log return over the window.', null=True)),
                ('abs_ret', models.FloatField(blank=True, null=True)),
                ('abnormal_ret', models.FloatField(blank=True, help_text='Observed minus matched-normal. This is what makes it an event study rather than a picture of a move (§6.1).', null=True)),
                ('realized_vol', models.FloatField(blank=True, null=True)),
                ('mfe', models.FloatField(blank=True, help_text='Maximum favourable excursion.', null=True)),
                ('mae', models.FloatField(blank=True, help_text='Maximum adverse excursion.', null=True)),
                ('spread_avg', models.FloatField(blank=True, null=True)),
                ('n_bars', models.IntegerField(default=0)),
                ('bars_missing', models.IntegerField(default=0)),
                ('is_outlier', models.BooleanField(default=False)),
                ('engine_version', models.CharField(db_index=True, max_length=32)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('event_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='calendar_data.eventrelease')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.instrument')),
                ('price_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
            options={
                'ordering': ['event_release', 'instrument', 'horizon'],
                'indexes': [models.Index(fields=['instrument', 'horizon', 'engine_version'], name='studies_eve_instrum_04a20a_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_release', 'instrument', 'price_source', 'horizon', 'window_scheme', 'engine_version'), name='uniq_event_impact')],
            },
        ),
        migrations.CreateModel(
            name='DecayCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('A', 'A — event-only (timestamps + price)'), ('B', 'B — surprise-conditioned (needs the forecast column)')], max_length=1)),
                ('horizon', models.CharField(choices=[('-5d', '-5d'), ('-1d', '-1d'), ('-4h', '-4h'), ('-1h', '-1h'), ('-15m', '-15m'), ('-5m', '-5m'), ('+1m', '+1m'), ('+5m', '+5m'), ('+15m', '+15m'), ('+30m', '+30m'), ('+1h', '+1h'), ('+4h', '+4h'), ('+1d', '+1d'), ('+3d', '+3d'), ('+1w', '+1w'), ('+2w', '+2w'), ('+1M', '+1M')], max_length=16)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('std_error', models.FloatField(blank=True, null=True)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('p_raw', models.FloatField(blank=True, null=True)),
                ('p_fdr', models.FloatField(blank=True, help_text='Benjamini–Hochberg, beside the raw p (§6.6).', null=True)),
                ('detectability_floor', models.FloatField(blank=True, help_text="Smallest effect this n could have detected here, so a null reads as 'no effect larger than X' (§3.2).", null=True)),
                ('n', models.IntegerField(default=0)),
                ('attribution_confidence', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='low', max_length=8)),
                ('regime', models.CharField(blank=True, choices=[('pre_crisis', 'pre-crisis (2007–08)'), ('crisis', 'crisis (2008–09)'), ('zirp_qe', 'ZIRP/QE (2010–15)'), ('normalisation', 'normalisation (2015–19)'), ('covid', 'COVID (2020–21)'), ('inflation_hiking', 'inflation/hiking (2022–23)'), ('post_hiking', 'post-hiking (2024–)')], max_length=20)),
                ('outlier_policy', models.CharField(choices=[('include', 'include'), ('flag', 'flag (default)'), ('winsorise', 'winsorise'), ('exclude', 'exclude')], default='flag', max_length=12)),
                ('engine_version', models.CharField(max_length=32)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decay_curves', to='calendar_data.indicator')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.instrument')),
                ('release_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decay_curves', to='calendar_data.releasegroup')),
                ('study_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curves', to='studies.studyrun')),
            ],
            options={
                'ordering': ['instrument', 'horizon'],
                'indexes': [models.Index(fields=['instrument', 'mode', 'engine_version'], name='studies_dec_instrum_13c335_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('indicator__isnull', False), ('release_group__isnull', True)), models.Q(('indicator__isnull', True), ('release_group__isnull', False)), _connector='OR'), name='curve_targets_exactly_one_of_indicator_or_group')],
            },
        ),
        migrations.AddConstraint(
            model_name='studyspec',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_spec_version'),
        ),
    ]
