# Generated by Django 5.2.17 on 2026-09-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decaycurve',
            name='mode',
            field=models.CharField(choices=[('A', 'A — event-only (timestamps + price)'), ('direction', 'direction — signed response to the change vs previous'), ('B', 'B — surprise-conditioned (needs the forecast column)')], max_length=16),
        ),
    ]
