# Generated by Django 5.2.17 on 2026-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_decaycurve_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='decaycurve',
            name='abs_ratio',
            field=models.FloatField(blank=True, help_text='Mode A: mean move over mean matched-normal move. 1.0 is normal.', null=True),
        ),
        migrations.AddField(
            model_name='decaycurve',
            name='baseline_n',
            field=models.IntegerField(blank=True, help_text="Median matched weeks behind each release's normal.", null=True),
        ),
        migrations.AddField(
            model_name='decaycurve',
            name='n_outliers',
            field=models.IntegerField(default=0, help_text='Flagged rows at this horizon, whatever the policy did with them.'),
        ),
        migrations.AddField(
            model_name='eventimpact',
            name='baseline_abs_mean',
            field=models.FloatField(blank=True, help_text='The matched-normal absolute move this row is compared against.', null=True),
        ),
        migrations.AddField(
            model_name='eventimpact',
            name='baseline_n',
            field=models.IntegerField(default=0, help_text='Matched weeks behind the normal (§6.1 asks for twelve).'),
        ),
        migrations.AddField(
            model_name='eventimpact',
            name='outlier_reason',
            field=models.CharField(blank=True, help_text="Why the row is flagged: a registered market event inside the window, or its distance from the pairing's median (§4.6).", max_length=200),
        ),
        migrations.AlterField(
            model_name='decaycurve',
            name='r_squared',
            field=models.FloatField(blank=True, help_text='Direction fits only. Mode A reads abs_ratio.', null=True),
        ),
    ]
