# Generated by Django 5.2.17 on 2026-09-10 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('calendar', 'calendar / events'), ('price', 'price'), ('actuals', 'actuals / statistics'), ('reference', 'reference')], max_length=16)),
                ('base_url', models.URLField(blank=True)),
                ('timezone_rule', models.CharField(blank=True, help_text="Human-readable clock rule, e.g. 'fixed UTC-5, no DST' or 'MT5 trade server time, DST-corrected'.", max_length=200)),
                ('fetch_policy_json', models.JSONField(blank=True, default=dict, help_text='Rate limits, cadence, retry policy. §5.4: politeness is self-interested here.')),
                ('terms_note', models.TextField(blank=True)),
                ('robots_status', models.CharField(choices=[('allowed', 'allowed'), ('restricted', 'restricted — see terms note'), ('disallowed', 'disallowed'), ('n_a', 'not applicable (local / API)'), ('unchecked', 'unchecked')], default='unchecked', max_length=16)),
                ('gives', models.CharField(blank=True, help_text='Which fields this source supplies (§5.1/§5.2).', max_length=300)),
                ('depth_note', models.CharField(blank=True, help_text='Known or measured history depth.', max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('supports_date_range', models.BooleanField(default=True, help_text="False for feeds that only ever return 'now', e.g. the ForexFactory weekly feed.")),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('health', models.CharField(choices=[('unknown', 'never fetched'), ('ok', 'ok'), ('degraded', 'degraded'), ('failing', 'failing'), ('disabled', 'disabled')], default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.SlugField(max_length=64)),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('cancelled', 'cancelled')], db_index=True, default='queued', max_length=16)),
                ('progress', models.FloatField(default=0.0, help_text='0.0 – 1.0')),
                ('message', models.CharField(blank=True, max_length=300)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sources_job_status_316b70_idx')],
            },
        ),
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='running', max_length=16)),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('rows_seen', models.IntegerField(default=0)),
                ('rows_new', models.IntegerField(default=0)),
                ('rows_changed', models.IntegerField(default=0)),
                ('rows_unmapped', models.IntegerField(default=0)),
                ('error_text', models.TextField(blank=True)),
                ('parser_version', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fetch_run', to='sources.job')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='sources.source')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RawSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.TextField(blank=True)),
                ('path', models.TextField(help_text='Relative to settings.RAW_DIR.')),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('fetch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sources.fetchrun')),
            ],
            options={
                'ordering': ['fetched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fetchrun',
            index=models.Index(fields=['source', '-started_at'], name='sources_fet_source__cc3529_idx'),
        ),
    ]
