# Generated by Django 5.2.17 on 2026-09-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchrun',
            name='bars_written',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='preview_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='sample_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='source',
            name='config_json',
            field=models.JSONField(blank=True, default=dict, help_text='Operator-editable settings the collector reads: which DBnomics series to pull, where the MT5 export lands, an API key. §0a — what a source collects is configuration, not code.'),
        ),
    ]
